language: node_js
node_js:
  - 15

jobs:
  include:
    - stage: tests and code coverage
      script:
        - cd library
        - yarn
        - yarn run test
        - sed -i "s/\.\.\/\.\.\///g" coverage/lcov.info

before_deploy:
  - yarn run doc
  - touch ../docs/.nojekyll
  - npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"

# Only when deploying a new release
deploy:
  # Deploys package on NPM
  - provider: script
    skip_cleanup: true
    script: yarn run build && cp ../README.md dist && cp ../LICENSE dist && sed -i "s/TRAVIS_TAG/$TRAVIS_TAG/g" ./dist/package.json && npm publish ./dist
    on:
      tags: true
  # Generates documentation
  - provider: pages
    skip_cleanup: true
    keep_history: true
    target_branch: master
    github_token: $GITHUB_TOKEN
    on:
      tags: true

# Coveralls is executed at the very end to prevent it from making deployment fail in case of error
after_success:
  - node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
